### PR TITLE
Add Lowest common ancestor algorithm

### PR DESCRIPTION
**Pull request by Hamada14**
In graph theory and computer science, the lowest common ancestor (LCA) of two nodes v and w in a tree or directed a cyclic graph (DAG) T is the lowest (i.e. deepest) node that has both v and w as descendants, where we define each node to be a descendant of itself (so if v has a direct connection from w, w is the lowest common ancestor).

There's many methods to find the LCA, one can be using Euler tour and a segment tree or by using Binary lifting which is the implemented method.

### CODE REVIEW

**Comment by xtaci** [comment]
please modify your code with OOP concept, and conform to C++11 standards with detailed comments.

**Comment by Hamada14** [comment]
Thanks a lot for the advice, I'll divide it into a .h and .cpp and apply OOP concepts 👍

**Comment by Hamada14** [comment]
I have confirmed to C++11 standards and added detailed comments describing the flow of the algorithm.

**Comment by xtaci** [comment]
please make changes to README.md too, add entry to your alg.

**Pull request merged**
